# These are supported funding model platforms

github: [thiennp]
open_collective: guardz-axios
ko_fi: nguyenphongthien
tidelift: npm/guardz
liberapay: ~1889616
issuehunt: nguyenphongthien
custom: ["https://github.com/thiennp/guardz-axios#sponsors"] 